background #0f1416
foreground #dee3e6
cursor #dee3e6
cursor_text_color #0f1416
selection_background #85d1e8
selection_foreground #0f1416
url_color #c0c4eb
active_tab_foreground #0f1416
active_tab_background #85d1e8
inactive_tab_foreground #dee3e6
inactive_tab_background #1b2022
color0 #0f1416
color1 #ffb4ab
color2 #b2cbd3
color3 #c0c4eb
color4 #85d1e8
color5 #40484b
color6 #004e5d
color7 #dee3e6
color8 #1b2022
color9 #ffb4ab
color10 #b2cbd3
color11 #c0c4eb
color12 #85d1e8
color13 #40484b
color14 #004e5d
color15 #dee3e6
