[ColorScheme]
active_text=#a9b1d6
disabled_text=#787c99
highlight=#7aa2f7
highlighted_text=#1a1b26
link=#7aa2f7
link_visited=#9d7cd8
window=#1a1b26
window_text=#a9b1d6
base=#1f2335
base_text=#a9b1d6
button=#24283b
button_text=#a9b1d6
tooltip_base=#1f2335
tooltip_text=#a9b1d6
